-- MySQL Script generated by MySQL Workbench
-- Mon Mar 11 21:18:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema coleta_pericles
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coleta_pericles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coleta_pericles` DEFAULT CHARACTER SET utf8 ;
USE `coleta_pericles` ;

-- -----------------------------------------------------
-- Table `coleta_pericles`.`animal_estimacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coleta_pericles`.`animal_estimacao` (
  `cod_animal` INT NOT NULL AUTO_INCREMENT,
  `nome_animal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_animal`),
  UNIQUE INDEX `nome_animal_UNIQUE` (`nome_animal` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coleta_pericles`.`clima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coleta_pericles`.`clima` (
  `cod_clima` INT NOT NULL AUTO_INCREMENT,
  `descr_clima` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_clima`),
  UNIQUE INDEX `descr_clima_UNIQUE` (`descr_clima` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coleta_pericles`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coleta_pericles`.`pessoa` (
  `cod_pessoa` INT NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `idade` INT NOT NULL,
  PRIMARY KEY (`cod_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coleta_pericles`.`bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coleta_pericles`.`bebida` (
  `cod_bebida` INT NOT NULL AUTO_INCREMENT,
  `nome_bebida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_bebida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coleta_pericles`.`hobby`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coleta_pericles`.`hobby` (
  `cod_hobby` INT NOT NULL AUTO_INCREMENT,
  `nome_hobby` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_hobby`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coleta_pericles`.`pesquisa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coleta_pericles`.`pesquisa` (
  `cod_pesquisa` INT NOT NULL,
  `data_pesquisa` DATE NOT NULL,
  `cod_animal` INT NOT NULL,
  `cod_clima` INT NOT NULL,
  `cod_hobby` INT NOT NULL,
  `cod_bebida` INT NOT NULL,
  `cod_pessoa` INT NOT NULL,
  PRIMARY KEY (`cod_pesquisa`),
  INDEX `fk_pesquisa_animal_estimacao_idx` (`cod_animal` ASC) VISIBLE,
  INDEX `fk_pesquisa_clima1_idx` (`cod_clima` ASC) VISIBLE,
  INDEX `fk_pesquisa_hobby1_idx` (`cod_hobby` ASC) VISIBLE,
  INDEX `fk_pesquisa_bebida1_idx` (`cod_bebida` ASC) VISIBLE,
  INDEX `fk_pesquisa_pessoa1_idx` (`cod_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_pesquisa_animal_estimacao`
    FOREIGN KEY (`cod_animal`)
    REFERENCES `coleta_pericles`.`animal_estimacao` (`cod_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_clima1`
    FOREIGN KEY (`cod_clima`)
    REFERENCES `coleta_pericles`.`clima` (`cod_clima`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_hobby1`
    FOREIGN KEY (`cod_hobby`)
    REFERENCES `coleta_pericles`.`hobby` (`cod_hobby`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_bebida1`
    FOREIGN KEY (`cod_bebida`)
    REFERENCES `coleta_pericles`.`bebida` (`cod_bebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_pessoa1`
    FOREIGN KEY (`cod_pessoa`)
    REFERENCES `coleta_pericles`.`pessoa` (`cod_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
